name: mtw-env
channels:
  - conda-forge
dependencies:
  - python=3.13

  # Core scientific computing
  - numpy
  - pandas
  - scipy

  # Plotting
  - matplotlib

  # Parallelization
  - joblib

  # Performance acceleration
  - numba

  # Packaging support
  - pip